# Generated by Django 4.2 on 2023-08-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='state',
            new_name='country',
        ),
    ]
